server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        #采样率值介于0到1之间，1表示全部采集
      probability: 1


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    druid:
      validation-query: select 1
      test-while-idle: true

mybatis:
  mapper-locations: com/zhou/mapper/*.xml
  type-aliases-package: com.zhou.entities
#  config-location: classpath:mybatis-config.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
#    客户点名称
    instance-id: payment8001
#    访问路径可以显示ip地址
    prefer-ip-address: true
#    eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 1
#    eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将删除服务
#    lease-expiration-duration-in-seconds: 2