
server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    druid:
      validation-query: select 1
      test-while-idle: true

mybatis:
  mapper-locations: com/zhou/mapper/*.xml
  type-aliases-package: com.zhou.entities
#  config-location: classpath:mybatis-config.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    #    \u5BA2\u6237\u70B9\u540D\u79F0
    instance-id: payment8002
    #    \u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793Aip\u5730\u5740
    prefer-ip-address: true
