server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: 192.168.31.183:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    druid:
      validation-query: select 1
      test-while-idle: true

mybatis:
  mapper-locations: com/zhou/mapper/*.xml
  type-aliases-package: com.zhou.entities

